In [1]:
import tensorflow as tf

In [2]:
tf.range(9)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [3]:
x = tf.range(start=1, limit=10, delta=2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [5]:
x = tf.cast(x, dtype=tf.float64)
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


In [6]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])
z = tf.add(x,y)
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
